
## Python Fundamentals

In [106]:
import numpy as np


### 1. Create a 2x2 arraay of ints with ones on the diagonal and zeros elsewhere

In [107]:
np.eye(2, dtype=np.int64 )

array([[1, 0],
       [0, 1]])

### 2. Create an array of 16 evenly spaced numbers between 0 and 1

In [108]:
np.linspace(0, 1, num=16 )

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])

### 3. Create an array of shape (3, 3) filled with zeros

In [109]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 4. What is a ufunc

In [110]:
print("univeral function: a function which operates on ndarrays element-wise.")

univeral function: a function which operates on ndarrays element-wise.


### 5. What Would be the output?

```python
import numpy as np

a = np.arange(15).reshape(3, 5)

print(
      a.shape,
      a.ndim,
      a.dtype,
      a.size,
      sep='\n',
)
```


In [111]:
a = np.arange(15).reshape(3, 5)

print(
      a.shape,
      a.ndim,
      a.dtype,
      a.size,
      sep='\n',
)

# Basic attributes of an ndarray.


(3, 5)
2
int64
15


### 6. What would be the output?

```python
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.arange(4)

print(a - b)
print(a)
```


In [112]:

a = np.array([10, 20, 30, 40])
b = np.arange(4)

print(a - b)
print(a)


# Arithmetic operators on arrays apply elementwise.
# A new array is created and filled with the results.

[10 19 28 37]
[10 20 30 40]


### 7.  What would be the output?

```python
import numpy as np

a = np.array([10, 20, 30, 40])

print((a - 5) < 18)
```

In [113]:
a = np.array([10, 20, 30, 40])

print((a - 5) < 18)

[ True  True False False]


### 8. What would be the output?

```python
import numpy as np

a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])

print(a * b)
```

In [114]:

a = np.array([[1, 1], [0, 1]])
b = np.array([[2, 0], [3, 4]])

print(a * b)

# Arithmetic operators on arrays apply elementwise.
# A new array is created and filled with the results.
# For matrix multiplication use @

[[2 0]
 [0 4]]


### 9. What would be the output?

```python
import numpy as np

a = np.array([1, 2, 3, 4])
b = a
a += 1
print(a)
print(b)
```

In [115]:

a = np.array([1, 2, 3, 4])
b = a
a += 1
print(a)
print(b)

# Arrays are mutable.
# Augmented assignment modifies an object in place by default.

[2 3 4 5]
[2 3 4 5]


### 10. Numpy. When operating with arrays of different types the resulting array's type is [...], a behavior known as [...].

In [116]:
# behavior known as upcasting.

### 11. What would be the output?

```python
import numpy as np

a = np.arange(4).reshape(2, 2)
print(a.sum())
print(np.sum(a))
```

In [117]:
a = np.arange(4).reshape(2, 2)
print(a.sum())
print(np.sum(a))

# Many ndarray methods are mirrored by functions in the outermost numpy namespace.


6
6


### 13. What would be the output?

```python
import numpy as np

a = np.array(
    [[ 0, 1, 2, 3],
     [ 4, 5, 6, 7],
     [ 8, 9, 10, 11]]
    )

print(a.sum(axis=0))
```


In [118]:

a = np.array(
    [[ 0, 1, 2, 3],
     [ 4, 5, 6, 7],
     [ 8, 9, 10, 11]]
    )

print(a.sum(axis=0))

# Taking the sum, rolling over rows.

# Extra
print(a.sum(axis=1))


[12 15 18 21]
[ 6 22 38]


### 14. What would be the output?

```python
import numpy as np

a = np.array(
    [[ 0, 1, 2, 3],
     [ 4, 5, 6, 7],
     [ 8, 9, 10, 11]]
    )

print(a.cumsum(axis=1)
```

In [119]:
a = np.array(
    [[ 0, 1, 2, 3],
     [ 4, 5, 6, 7],
     [ 8, 9, 10, 11]]
    )

print(a.cumsum(axis=1))

# Take cumulative sums, rolling over columns.

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


### 15. Output? 
```python
import numpy as np

cond = np.array([True, False, True, True]).reshape(2, 2)
x = np.arange(1, 5).reshape(2, 2)
y = np.arange(5, 9).reshape(2, 2)
print(np.where(cond, x, y))
```

In [120]:

cond = np.array([True, False, True, True]).reshape(2, 2)
x = np.arange(1, 5).reshape(2, 2)
y = np.arange(5, 9).reshape(2, 2)
print(np.where(cond, x, y))

## np.where() makes an array by selecting elements from x or y depending on condition.

[[1 6]
 [3 4]]


### 16. Ouput?

```python
import numpy as np

cond = np.array([True, False])
x = np.arange(1, 5).reshape(2, 2)
y = 17
print(np.where(cond, x, y))
```

In [121]:

cond = np.array([True, False])
x = np.arange(1, 5).reshape(2, 2)
y = 17

print(np.where(cond, x, y))

# np.where() makes an array from elements chosen from x or y depending on condition. 
# The arguments are broadcast to the same shape.

# cond has a shape of (2,) (2 elements)
# x has a shape of (2, 2) (4 elements)
# y has a shape of () (1 scalar element)

# Broadcasting. NumPy automatically stretches smaller arrays to match the size of the largest array.
# To make them match, NumPy stretches cond and y to become (2, 2) matrices.

# cond: When matching a 1D array to a 2D array, NumPy duplicates the row downwards for every row in x.
# The [True, False] line gets repeated for the second row.
# [True False]
# [True False]

# x:
# [1 2]
# [3 4]


# y: The scalar 17 is the easiest. NumPy just copies it to fill every position of a \(2 \times 2\)
# [17 17]
# [17 17]


# np.where(cond, x, y)
# [1 17]
# [3 17]


[[ 1 17]
 [ 3 17]]


### 17. Output

```python
import numpy as np

a = np.arange(10)**2
a[::2] = -1
print(a)
```

In [122]:
a = np.arange(10)**2
a[::2] = -1
print(a)

[-1  1 -1  9 -1 25 -1 49 -1 81]


### 19. Output ?

```python
import numpy as np

a = np.fromfunction(
    lambda x, y: 10 * x + y,
    (3, 3),
)

print(a)
```

In [123]:
a = np.fromfunction(
    lambda x, y: 10 * x + y,
    (3, 3),
)

print(a)

# np.fromfunction() makes an array by executing a function over each coordinate.

# The np.fromfunction function creates an array by running your lambda function on the index coordinates of each element.
# The Shape (3, 3): This creates a grid with 3 rows and 3 columns.
# The Inputs x and y: NumPy passes the row indices to x and the column indices to y.

# NumPy generates two internal index matrices for a (3,3) space:
# 1. Get the x and y coordinate grids
x, y = np.indices((3, 3))

print(x, y, sep="\n")

# Row Indices(X):
# [0 0 0]
# [1 1 1]
# [2 2 2]


# Cols Indices(Y):
# [0 1 2]
# [0 1 2]
# [0 2 2]


# -   **Top Row (`x = 0`)**:
#     -   `10*(0) + 0 = 0`
#     -   `10*(0) + 1 = 1`
#     -   `10*(0) + 2 = 2` 
# -   **Middle Row (`x = 1`)**:
#     -   `10*(1) + 0 = 10`
#     -   `10*(1) + 1 = 11`
#     -   `10*(1) + 2 = 12` 
# -   **Bottom Row (`x = 2`)**:
#     -   `10*(2) + 0 = 20`
#     -   `10*(2) + 1 = 21`
#     -   `10*(2) + 2 = 22`


[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]]
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


### 20. Output?

```python
import numpy as np

a = np.array(
    [[ 0, 1, 2, 3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33],
     [40, 41, 42, 43]]
)

print(a[2, 3])
print(a[0:5, 1])
print(a[:, 1])
print(a[1:3, :])
```

In [124]:
a = np.array(
    [[ 0, 1, 2, 3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33],
     [40, 41, 42, 43]]
)

print(a[2, 3])
print(a[0:5, 1])
print(a[:, 1])
print(a[1:3, :])

# Examples of basic indexing.
# Arrays have one index per axis.


23
[ 1 11 21 31 41]
[ 1 11 21 31 41]
[[10 11 12 13]
 [20 21 22 23]]


### 21. Output?

```python
import numpy as np

a = np.array(
    [[ 0, 1, 2, 3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33],
     [40, 41, 42, 43]]
)

print(a[-1])
print(a[-1, :])
print(a[-1, ...])
```

In [125]:
a = np.array(
    [[ 0, 1, 2, 3],
     [10, 11, 12, 13],
     [20, 21, 22, 23],
     [30, 31, 32, 33],
     [40, 41, 42, 43]]
)

print(a[-1])
print(a[-1, :])
print(a[-1, ...])

# Missing indices are filled with colons as required.
# Or include the colon yourself, or use ellipsis.

[40 41 42 43]
[40 41 42 43]
[40 41 42 43]


### 22. Output?

```python
import numpy as np

a = np.array(
    [[0, 1],
     [10, 11]]
)

for x in a.flat:
    print(x)
```

In [130]:
a = np.array(
    [[0, 1],
     [10, 11]]
)

for x in a.flat:
    print(x)

# An array's flat attribute is an np.flatiter instance, which is similar to an iterator over the array's elements.

# Extra

# Use .flat in a for loop to save memory. It does not allocate memory for a new 1D array.

# You can overwrite specific multi-dimensional elements using a single flat index.
arr = np.array([[1,2], [3, 4]])
a.flat[2] = 99
print(arr)

# You can replace multiple items at once using 1D slice logic on a 2D or 3D array.
arr.flat[1:3] = [0, 0]
print(arr)



0
1
10
11
[[1 2]
 [3 4]]
[[1 0]
 [0 4]]


### 23. Output?

```python
import numpy as np

a = np.array(
    [[0, 1],
     [10, 11]]
)

for x in a:
    print(x)
```

In [127]:
a = np.array(
    [[0, 1],
     [10, 11]]
)

for x in a:
    print(x)

# Iterating over an array is done over its first axis.

[0 1]
[10 11]


### 24. Output?

```python
import numpy as np

a = np.arange(8).reshape(2, 4)
b = a.T
print(a.shape, b.shape)
b[0, 0] = 7
print(a)

```

In [128]:
a = np.arange(8).reshape(2, 4)


# a.T returns a new transposed array, which views the same data as a.
# Rule of thumb: views are returned when possible.


# Creates a transposed view b. Its shape becomes \(4 \times 2\). It points to the exact same flat line in memory, but reads it vertically.
b = a.T

print(a.shape, b.shape)

# You target the top-left element of b. That slot shares the physical memory location with the top-left element of a (which was 0).
# The value in that shared memory cell changes to 7.
b[0, 0] = 7

print(a)


(2, 4) (4, 2)
[[7 1 2 3]
 [4 5 6 7]]


### 25. Output?
```python
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a.ravel())
print(a)
```

In [ ]:
a = np.arange(8).reshape(2, 4)
print(a.ravel())
print(a)

# The ravel() method returns a new flattened array. Not in place!

# Extra

# ravel(): Returns a view by default. It is highly execution-speed efficient and memory-friendly because it skips allocating  new space.

# flatten(): Always forces a deep copy. 
# Changes to your flattened output will never impact your original array data, but it consumes more system memory for large structures

arr = np.array([[1, 2, 3], [4, 5, 6]])

# Both methods yield the exact same result:
print(arr.ravel())  # [1 2 3 4 5 6]

# Shared Reference: If you change an element in the flattened view, the original array mutates:

flat = arr.ravel()
flat[0] = 99
print(arr)  # [[99,  2,  3], [ 4,  5,  6]]


[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]

[1 2 3 4 5 6]
[[99  2  3]
 [ 4  5  6]]


### 26. Output?

```python
import numpy as np

a = np.arange(8).reshape(2, -1)
print(a)
```

In [136]:
a = np.arange(8).reshape(2, -1)
print(a)

# Pass -1 to reshape() to calculate the dimension automatically.

[[0 1 2 3]
 [4 5 6 7]]


### 27. Output?

```python
import numpy as np

a = np.array(
    [[1, 2],
     [3, 4]]
)

b = np.array(
    [[5, 6],
     [7, 8]]
)

print(np.vstack((a, b)))
print(np.hstack((a, b)))
```


In [154]:
a = np.array(
    [[1, 2],
     [3, 4]]
)

b = np.array(
    [[5, 6],
     [7, 8]]
)

print(np.vstack((a, b)))
print(np.hstack((a, b)))

# np.vstack() stacks along arrays' first axes and np.hstack() stacks along arrays' second axes.
# Note the tuples!


# Extra
print()
# np.concatenate() joins a sequence of arrays along an existing axis. 
# You must pass the input arrays as a single container (like a tuple or list), 
# and they must have identical shapes except along the axis you are combining. Note that starting with NumPy 2.0, 
# you can also use np.concat as a convenient shorthand


# Vertical Stacking (axis=0)Combines rows. The arrays must have the same number of columns.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = np.concatenate((a, b), axis=0)
print(result)
# Output:
# [[1 2]
#  [3 4]
#  [5 6]]

# Horizontal Stacking (axis=1)Combines columns. The arrays must have the same number of rows.pythona = np.array([[1, 2], [3, 4]])
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

result = np.concatenate((a, b), axis=1)
print(result)
# Output:
# [[1 2 5]
#  [3 4 6]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


### 28. Output?

```python
import numpy as np

a = np.arange(12).reshape(2, 6)

print(np.hsplit(a, 2))
````

In [146]:
a = np.arange(12).reshape(2, 6)

print(np.hsplit(a, 2))

# np.hsplit() splits an array along its horizontal axis and returns the subarrays in a list.

# Extra
a_1, a_2 = np.hsplit(a, 2)

print(a_1, a_2, sep="\n")

[array([[0, 1, 2],
       [6, 7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]])]
[[0 1 2]
 [6 7 8]]
[[ 3  4  5]
 [ 9 10 11]]


### 29. Output?

```python
import numpy as np

a = np.arange(6).reshape(2, 3)
b = a
print(b is a)
```

In [148]:
a = np.arange(6).reshape(2, 3)
b = a
print(b is a)

# Assignment never copies data.

True


### 30. Effect?
```python
np.eye(2, dtype=int)
```

In [ ]:
# create a 2x2 array of ints with ones on the diagonal and zeros elsewhere

np.eye(2, dtype=int)


array([[1, 0],
       [0, 1]])

### 31. Effect? 
```python
np.linspace(0, 1, 16)
```

In [150]:
# create an array of 16 evenly spaced numbers between 0 and 1
np.linspace(0, 1, 16) 

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])

### 32. Effect? 
```python
np.zeros((3, 3))
```


In [151]:
# create an array of shape (3, 3) filled with zeros

np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])