### Numpy

In [149]:
import numpy as np

print(f"numpy(np {np.__version__} is imported")


numpy(np 2.5.1 is imported


In [150]:
# Regular list

""" 
Apple = 1
Orange = 2
Grapes = 3
Kiwi = 4
"""

fruit_list : list[int] = [1,2,3,4]

double_fruit_list: list[int] = fruit_list *2;

print(fruit_list)

print(double_fruit_list)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [151]:
# Numpy array, faster than regular python list.

np_fruit_array = np.array(fruit_list)

multiplied_np_fruit_array = np_fruit_array * 2;

print(f"Numpy array\t\t {np_fruit_array} of type {type(np_fruit_array)}")
print(f"Multiplied Numpy array   {multiplied_np_fruit_array} of type {type(multiplied_np_fruit_array)}")


Numpy array		 [1 2 3 4] of type <class 'numpy.ndarray'>
Multiplied Numpy array   [2 4 6 8] of type <class 'numpy.ndarray'>


#### 1D, 2D and 3D Array Dimensions

![1_3D_array](https://i0.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)

In [152]:
# Multi Dimensional Numpy Array


array_0d = np.array(1)

print(array_0d, f"of type {type(array_0d)} having {array_0d.ndim} Dimensions\n")


array_1d = np.array([1, 2, 3])

print(array_1d, f"of type {type(array_1d)} having {array_1d.ndim} Dimensions\n")


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d, f"of type {type(array_2d)} having {array_2d.ndim} Dimensions\n")


1 of type <class 'numpy.ndarray'> having 0 Dimensions

[1 2 3] of type <class 'numpy.ndarray'> having 1 Dimensions

[[1 2 3]
 [4 5 6]
 [7 8 9]] of type <class 'numpy.ndarray'> having 2 Dimensions



In [153]:
# Acesss array elements in 2D Numpy Arrray

print(array_2d, "\n")

print(f"Shaped of 2d Array {array_2d.shape}")

array_2d_first_row = array_2d[0]

print(f"First Row {array_2d_first_row}")

array_2d_first_col = array_2d[:, 0]

print(f"First Coloumn {array_2d_first_col}")

array_2d_first_element = array_2d[0][1]

print(f"First element {array_2d_first_element}")

array_2d_last_element = array_2d[-1][-1]

print(f"Last element {array_2d_last_element}")

array_2d_second_third_row = array_2d[1:]

print(f"Second-Third Row \n{array_2d_second_third_row}\n")

array_2d_last_row = array_2d[-1]  # array_2d[-1:] 

print("Last Row", array_2d_last_row)

array_2d_last_col = array_2d[ :, -1]

print("Last Col", array_2d_last_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Shaped of 2d Array (3, 3)
First Row [1 2 3]
First Coloumn [1 4 7]
First element 2
Last element 9
Second-Third Row 
[[4 5 6]
 [7 8 9]]

Last Row [7 8 9]
Last Col [3 6 9]


In [154]:
# 3d and 4d array

array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(array_3d, f"{array_3d.ndim}D", f"Shape {array_3d.shape}", sep="\t")

array_4d = np.array([[
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], 

                                              [[[1, 2, 3],[4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]],

                                              [[[1, 2,3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
                                              ])

print(array_4d, f"{array_4d.ndim}D",f"Shape {array_4d.shape}" , sep="\t",)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]	3D	Shape (3, 3, 3)
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]	4D	Shape (3, 3, 3, 3)


In [155]:
## Access Elements from 3d Array

print(array_3d, "\n")

array_3d_first_layer = array_3d[0]

print(f"First Layer: \n{array_3d_first_layer}\n")

array_3d_last_layer = array_3d[-1]

print(f"Last Layer: \n{array_3d_last_layer}\n")

array_3d_second_third_layers = array_3d[1:]

print(f"Second-Third Layers: \n{array_3d_second_third_layers}\n")

array_3d_first_layer_second_row = array_3d[0][1] # Or array_3d[0, 1]

print(f"First Layer Second Row {array_3d_first_layer_second_row}")

array_3d_second_layer_last_col = array_3d[1, :, -1] 

print(f"Second Layer Last Col, {array_3d_second_layer_last_col}")


num_891_from_array_3d: int = int(str(array_3d[0, 2, 1]) + str(array_3d[1, 0, 0]) + str(array_3d[2, 0, 0 ]))

print(f"{num_891_from_array_3d}")




[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] 

First Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Last Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second-Third Layers: 
[[[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

First Layer Second Row [4 5 6]
Second Layer Last Col, [7 4 1]
891


In [156]:
# Slicing with Numpy, note all the slices are just view to the actual array, if you want independent
# array use .copy() method eg. my_array.copy() or my_array[:].copy() or my_array.T.copy() for transponse matric

my_array = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10 , 11, 12], 
    [13, 14, 15, 16 ]
]) # Shape (4, 4)

print("My Array:\n", my_array, "\n")


my_array_half_slice = my_array[:2, :]

print(f"First Half Slice: \n{my_array_half_slice}\n")

my_array_other_half_slice = my_array[2:,: ]

print(f"Other Half Slice: \n{my_array_other_half_slice}\n")

my_array_first_row  = my_array[-1]

print(f"First Row: \n{my_array_first_row}\n")

my_array_second_row_third_fourth_element_slice = my_array[1, 2:] 

print(f"Third & fourth Element from second row: {my_array_second_row_third_fourth_element_slice}")

my_array_reverse_first_row = my_array[0][::-1]

print(f"First row reversed {my_array_reverse_first_row}")

my_array_same_row_order_reverse_elements  = my_array[:, ::-1]

print(f"Rows with reversed elements\n{my_array_same_row_order_reverse_elements}")

my_array_alternate_rows = my_array[::2]

print("Alternating rows\n", my_array_alternate_rows)

my_array_second_col = my_array[:, 1]

print("Second Row\n", my_array_second_col)


My Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

First Half Slice: 
[[1 2 3 4]
 [5 6 7 8]]

Other Half Slice: 
[[ 9 10 11 12]
 [13 14 15 16]]

First Row: 
[13 14 15 16]

Third & fourth Element from second row: [7 8]
First row reversed [4 3 2 1]
Rows with reversed elements
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Alternating rows
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Second Row
 [ 2  6 10 14]


In [157]:
# More slicing operations

print(my_array)

# Stepping
my_array_in_between_elements_in_rows = my_array[:, ::2]

print("Alternation elements in the rows:\n", my_array_in_between_elements_in_rows)

my_array_transpose = my_array.T

print("Transpose of my_array\n", my_array_transpose)

my_array_second_to_fourth_cols_transpose = my_array[:, 0:4].transpose() # or T or np.transponse(my_array_second_to_fourth_cols)

print("Second-Fourth Cols in the array\n", my_array_second_to_fourth_cols_transpose)


my_array_1_4_col = my_array[:, [0, 3]]

print("First and fourth col\n", my_array_1_4_col)

first_two_rows_first_two_cols = my_array[:2, :2]

print("First two rows and firt two cols:\n",first_two_rows_first_two_cols )

first_two_rows_last_two_cols = my_array[:2, 2:]

print("First two rows and last two cols:\n",first_two_rows_last_two_cols )

last_two_rows_first_two_cols = my_array[2:, :2]

print("Last two rows, first two cols\n", last_two_rows_first_two_cols, "Last two rows, last two cols\n", my_array[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Alternation elements in the rows:
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Transpose of my_array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Second-Fourth Cols in the array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
First and fourth col
 [[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]
First two rows and firt two cols:
 [[1 2]
 [5 6]]
First two rows and last two cols:
 [[3 4]
 [7 8]]
Last two rows, first two cols
 [[ 9 10]
 [13 14]] Last two rows, last two cols
 [[11 12]
 [15 16]]


In [158]:
import string

my_letters = np.append(list(string.ascii_lowercase),"_").reshape(3, 3, 3)

print(my_letters)

# Sun
sun : str = my_letters[2][0][0] + my_letters[2][0][2] + my_letters[1][1][1] 

print(f"{sun.title()} is sol in espanol")


[[['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' '_']]]
Sun is sol in espanol
