### Numpy

In [176]:

import string
import random as rnd
import secrets
import time
import numpy as np
from scipy import stats as st

print(f"numpy(np {np.__version__} is imported")


numpy(np 2.5.1 is imported


In [177]:
# Regular list

""" 
Apple = 1
Orange = 2
Grapes = 3
Kiwi = 4
"""

fruit_list : list[int] = [1,2,3,4]

double_fruit_list: list[int] = fruit_list *2;

print(fruit_list)

print(double_fruit_list)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [178]:
# Numpy array, faster than regular python list.

np_fruit_array = np.array(fruit_list)

multiplied_np_fruit_array = np_fruit_array * 2;

print(f"Numpy array\t\t {np_fruit_array} of type {type(np_fruit_array)}")
print(f"Multiplied Numpy array   {multiplied_np_fruit_array} of type {type(multiplied_np_fruit_array)}")


Numpy array		 [1 2 3 4] of type <class 'numpy.ndarray'>
Multiplied Numpy array   [2 4 6 8] of type <class 'numpy.ndarray'>


#### 1D, 2D and 3D Array Dimensions

![1_3D_array](https://i0.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)

In [179]:
# Multi Dimensional Numpy Array


array_0d = np.array(1)

print(array_0d, f"of type {type(array_0d)} having {array_0d.ndim} Dimensions\n")


array_1d = np.array([1, 2, 3])

print(array_1d, f"of type {type(array_1d)} having {array_1d.ndim} Dimensions\n")


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d, f"of type {type(array_2d)} having {array_2d.ndim} Dimensions\n")


1 of type <class 'numpy.ndarray'> having 0 Dimensions

[1 2 3] of type <class 'numpy.ndarray'> having 1 Dimensions

[[1 2 3]
 [4 5 6]
 [7 8 9]] of type <class 'numpy.ndarray'> having 2 Dimensions



In [180]:
# Acesss array elements in 2D Numpy Arrray

print(array_2d, "\n")

print(f"Shaped of 2d Array {array_2d.shape}")

array_2d_first_row = array_2d[0]

print(f"First Row {array_2d_first_row}")

array_2d_first_col = array_2d[:, 0]

print(f"First Coloumn {array_2d_first_col}")

array_2d_first_element = array_2d[0][1]

print(f"First element {array_2d_first_element}")

array_2d_last_element = array_2d[-1][-1]

print(f"Last element {array_2d_last_element}")

array_2d_second_third_row = array_2d[1:]

print(f"Second-Third Row \n{array_2d_second_third_row}\n")

array_2d_last_row = array_2d[-1]  # array_2d[-1:] 

print("Last Row", array_2d_last_row)

array_2d_last_col = array_2d[ :, -1]

print("Last Col", array_2d_last_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Shaped of 2d Array (3, 3)
First Row [1 2 3]
First Coloumn [1 4 7]
First element 2
Last element 9
Second-Third Row 
[[4 5 6]
 [7 8 9]]

Last Row [7 8 9]
Last Col [3 6 9]


In [181]:
# 3d and 4d array

array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(array_3d, f"{array_3d.ndim}D", f"Shape {array_3d.shape}", sep="\t")

array_4d = np.array([[
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], 

                                              [[[1, 2, 3],[4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]],

                                              [[[1, 2,3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
                                              ])

print(array_4d, f"{array_4d.ndim}D",f"Shape {array_4d.shape}" , sep="\t",)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]	3D	Shape (3, 3, 3)
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]	4D	Shape (3, 3, 3, 3)


In [182]:
## Access Elements from 3d Array

print(array_3d, "\n")

array_3d_first_layer = array_3d[0]

print(f"First Layer: \n{array_3d_first_layer}\n")

array_3d_last_layer = array_3d[-1]

print(f"Last Layer: \n{array_3d_last_layer}\n")

array_3d_second_third_layers = array_3d[1:]

print(f"Second-Third Layers: \n{array_3d_second_third_layers}\n")

array_3d_first_layer_second_row = array_3d[0][1] # Or array_3d[0, 1]

print(f"First Layer Second Row {array_3d_first_layer_second_row}")

array_3d_second_layer_last_col = array_3d[1, :, -1] 

print(f"Second Layer Last Col, {array_3d_second_layer_last_col}")


num_891_from_array_3d: int = int(str(array_3d[0, 2, 1]) + str(array_3d[1, 0, 0]) + str(array_3d[2, 0, 0 ]))

print(f"{num_891_from_array_3d}")




[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] 

First Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Last Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second-Third Layers: 
[[[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

First Layer Second Row [4 5 6]
Second Layer Last Col, [7 4 1]
891


In [183]:
# Slicing with Numpy, note all the slices are just view to the actual array, if you want independent
# array use .copy() method eg. my_array.copy() or my_array[:].copy() or my_array.T.copy() for transponse matric

my_array = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10 , 11, 12], 
    [13, 14, 15, 16 ]
]) # Shape (4, 4)

print("My Array:\n", my_array, "\n")


my_array_half_slice = my_array[:2, :]

print(f"First Half Slice: \n{my_array_half_slice}\n")

my_array_other_half_slice = my_array[2:,: ]

print(f"Other Half Slice: \n{my_array_other_half_slice}\n")

my_array_first_row  = my_array[-1]

print(f"First Row: \n{my_array_first_row}\n")

my_array_second_row_third_fourth_element_slice = my_array[1, 2:] 

print(f"Third & fourth Element from second row: {my_array_second_row_third_fourth_element_slice}")

my_array_reverse_first_row = my_array[0][::-1]

print(f"First row reversed {my_array_reverse_first_row}")

my_array_same_row_order_reverse_elements  = my_array[:, ::-1]

print(f"Rows with reversed elements\n{my_array_same_row_order_reverse_elements}")

my_array_alternate_rows = my_array[::2]

print("Alternating rows\n", my_array_alternate_rows)

my_array_second_col = my_array[:, 1]

print("Second Row\n", my_array_second_col)


My Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

First Half Slice: 
[[1 2 3 4]
 [5 6 7 8]]

Other Half Slice: 
[[ 9 10 11 12]
 [13 14 15 16]]

First Row: 
[13 14 15 16]

Third & fourth Element from second row: [7 8]
First row reversed [4 3 2 1]
Rows with reversed elements
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Alternating rows
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Second Row
 [ 2  6 10 14]


In [184]:
# More slicing operations

print(my_array)

# Stepping
my_array_in_between_elements_in_rows = my_array[:, ::2]

print("Alternation elements in the rows:\n", my_array_in_between_elements_in_rows)

my_array_transpose = my_array.T

print("Transpose of my_array\n", my_array_transpose)

my_array_second_to_fourth_cols_transpose = my_array[:, 0:4].transpose() # or T or np.transponse(my_array_second_to_fourth_cols)

print("Second-Fourth Cols in the array\n", my_array_second_to_fourth_cols_transpose)


my_array_1_4_col = my_array[:, [0, 3]]

print("First and fourth col\n", my_array_1_4_col)

first_two_rows_first_two_cols = my_array[:2, :2]

print("First two rows and firt two cols:\n",first_two_rows_first_two_cols )

first_two_rows_last_two_cols = my_array[:2, 2:]

print("First two rows and last two cols:\n",first_two_rows_last_two_cols )

last_two_rows_first_two_cols = my_array[2:, :2]

print("Last two rows, first two cols\n", last_two_rows_first_two_cols, "Last two rows, last two cols\n", my_array[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Alternation elements in the rows:
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Transpose of my_array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Second-Fourth Cols in the array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
First and fourth col
 [[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]
First two rows and firt two cols:
 [[1 2]
 [5 6]]
First two rows and last two cols:
 [[3 4]
 [7 8]]
Last two rows, first two cols
 [[ 9 10]
 [13 14]] Last two rows, last two cols
 [[11 12]
 [15 16]]


In [185]:

letters = string.ascii_lowercase

my_letters = np.append(list(letters), "_").reshape(3, 3,3)

print(my_letters)

sun : str = my_letters[2][0][0]  + my_letters[2][0][2] + my_letters[1][1][1]

print(f"Sol from espanol is {sun} in English")

[[['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' '_']]]
Sol from espanol is sun in English


### Scaler Arithemetic in Numy

In [186]:
my_array = np.array([1, 2, 3])

print(my_array, "\n")

print("+  2 ", my_array + 2)
print("-  4",my_array - 4)
print("/  3",my_array / 3)
print("%  2",my_array % 2)
print("** 2",my_array ** 2)

[1 2 3] 

+  2  [3 4 5]
-  4 [-3 -2 -1]
/  3 [0.33333333 0.66666667 1.        ]
%  2 [1 0 1]
** 2 [1 4 9]


### Vector Math Functions in Numpy 

In [187]:
print(my_array)

print("Transponse:\t", np.transpose(my_array)) # Or my_array.T or my_array.transpose()

print("Square root:\t", np.sqrt(my_array))

print("Pi value:\t", np.pi)

print("Round value:\t", np.round(my_array)) # Or my_array.round()

print("Floor value", np.floor(my_array))

print("Ceil value:\t", np.ceil(my_array)) 

[1 2 3]
Transponse:	 [1 2 3]
Square root:	 [1.         1.41421356 1.73205081]
Pi value:	 3.141592653589793
Round value:	 [1 2 3]
Floor value [1 2 3]
Ceil value:	 [1 2 3]


In [188]:
# Calcualte the radius as the area of circle from np.array of radii

radii_array = np.array([1, 2, 3])
circle_radii_area_array = np.pi * radii_array **2 

print(circle_radii_area_array)

[ 3.14159265 12.56637061 28.27433388]


### Comparsion operators in Numpy

In [189]:
students_scores = np.array([100, 70, 60, 23, 50, 80]) 
# students_marks: list[int] = [int(score) for score in students_scores]
students_marks: list[int]= students_scores.tolist()


print(students_marks)
print(students_scores)
print()

print(students_scores == 100 )
print([val == 100 for val in students_marks])
print()

# Sutdents, who score atleast 35, pass
print(students_scores >= 35) 
print([val >= 35  for val in students_marks])
print()


# Students, who score perfect 100, just get those student score
print(students_scores[students_scores == 100])
print([val for val in students_marks if val == 100])
print()

# Students, who score atleast 35, just get those student scores [Pass]
print(students_scores[students_scores >=35])
print([val for val in students_marks if val >=35 ])
print()

# Students, who score less than 35, just get those student scores [Fail] 
print(students_scores[students_scores<35])
print([val for val in students_marks if val <35])


[100, 70, 60, 23, 50, 80]
[100  70  60  23  50  80]

[ True False False False False False]
[True, False, False, False, False, False]

[ True  True  True False  True  True]
[True, True, True, False, True, True]

[100]
[100]

[100  70  60  50  80]
[100, 70, 60, 50, 80]

[23]
[23]


## Ways to create arrays with Numpy,Zeros, Ones, Reshape..

In [190]:
# Ones Array
ones_array = np.ones((3, 2, 4), dtype=int)
print(ones_array, "\n")

# Zeros Array

zeros_array = np.zeros((2, 3, 5),dtype=int)
print(zeros_array, "\n")

letters: list[str] = ["A", "Z", "D", "%", "C"]
my_letters = np.append(letters, values="W").reshape(2, 3)

print(my_letters)
print()

letters.append("W")
perfect_letters = np.array(letters).reshape(2, 3)

print(perfect_letters)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]] 

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]] 

[['A' 'Z' 'D']
 ['%' 'C' 'W']]

[['A' 'Z' 'D']
 ['%' 'C' 'W']]


## Broadcasting in Numpy

Performs operations on arrays with different shapes by virtually expanding dimensions, so they match the larger array's shape.

The two array's demensions(shape) have the same size.

OR

One of the array's dimensions(shape) has a size of 1.

![img](../images/broadcasting_in_numpy.png)

In [191]:
# 2D Array

array_2d  = np.array([[1, 2, 3, 4]])

array_2d_1col = np.array([[1], [2], [3], [4]])

print(f"{array_2d}\nShape:{array_2d.shape}\n")

print(f"{array_2d_1col}\nShape:{array_2d_1col.shape}")

# This two arrays statisfy our second condition where neither one dimension need to be 1
# (`1`, 4) & (4, `1`) Shape

print(f"{array_2d * array_2d_1col}, Shape: {(array_2d * array_2d_1col).shape}\n") # This works, we expand the vi

[[1 2 3 4]]
Shape:(1, 4)

[[1]
 [2]
 [3]
 [4]]
Shape:(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]], Shape: (4, 4)



In [192]:
# Creating multiplication table with numpy broadcasting..

array_1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array_2 = np.array([[1],[2], [3], [4], [5], [6], [7], [8], [9], [10]])

table = array_1 * array_2

print(table,f"Shape: {table.shape}" "\n")

for num in range(10): 
    print(f"Table {num+1}: ", table[num])

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] Shape: (10, 10)

Table 1:  [ 1  2  3  4  5  6  7  8  9 10]
Table 2:  [ 2  4  6  8 10 12 14 16 18 20]
Table 3:  [ 3  6  9 12 15 18 21 24 27 30]
Table 4:  [ 4  8 12 16 20 24 28 32 36 40]
Table 5:  [ 5 10 15 20 25 30 35 40 45 50]
Table 6:  [ 6 12 18 24 30 36 42 48 54 60]
Table 7:  [ 7 14 21 28 35 42 49 56 63 70]
Table 8:  [ 8 16 24 32 40 48 56 64 72 80]
Table 9:  [ 9 18 27 36 45 54 63 72 81 90]
Table 10:  [ 10  20  30  40  50  60  70  80  90 100]


In [193]:
# Broadcasting with same dimensions(shape)

array_1 = np.array([[1, 2], [3, 4], [5, 6]])

print(array_1, f"Shape: {array_1.shape}")

array_2 = np.array([10, 20])

print("\n",array_2, f"Shape: {array_2.shape}")

#Broadcast to bigger array aka, array_1 (shape: 3,2 )

array_3 = array_1 * array_2

print("\n",array_3, f"Shape: {array_3.shape}")



[[1 2]
 [3 4]
 [5 6]] Shape: (3, 2)

 [10 20] Shape: (2,)

 [[ 10  40]
 [ 30  80]
 [ 50 120]] Shape: (3, 2)


In [194]:
# Incompatible broadcasting and way to fix it
array_ones = np.ones((4, 3))
array_ones_1 = np.ones((4,2))

try:
    print(array_ones + array_ones_1)
except ValueError as err:
    print(f"Error: {err}, \n")

# Fix
a = np.ones((4, 3))  # Shape (4, 3)
print(a, f"Shape: {a.shape}")

b = np.array([1, 2, 3, 4])  # Shape (4,)
print(b, f"Shape: {b.shape}")
print()

# Directly adding a + b fails because (4,) pads to (1, 4), which doesn't match (4, 3)
# Fix: Insert a new dimension to make b shape (4, 1)
b_fixed = b[:, np.newaxis]  # Shape becomes (4, 1)
print(b_fixed, f"Shape: {b_fixed.shape}")

print(f"Finally: \n{a+b_fixed}, Shape: {(a + b_fixed).shape}")
# Output: (4, 3)


Error: operands could not be broadcast together with shapes (4,3) (4,2) , 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] Shape: (4, 3)
[1 2 3 4] Shape: (4,)

[[1]
 [2]
 [3]
 [4]] Shape: (4, 1)
Finally: 
[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]], Shape: (4, 3)


## Aggregation Functions (summarize data and typically return a single value)

In [195]:
# Sum: np.sum() or array.sum()

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

ar_sum = array.sum() # Get the sum of all elements in the array 
ar_sum_axis0 = np.sum(array,axis=0) # Get the sum of all elements in the array along axis 0 (columns)
ar_sum_axis1 = np.sum(array,axis=1) # Get the sum of all elements in the array along axis 1 (rows)

print("np Array\n", array)
print("np Array Sum", ar_sum)
print("np Array Sum along axis 0(columns):", ar_sum_axis0)
print("np Array Sum along axis 1(rows):", ar_sum_axis1)

 # Mean: np_mean = np.mean(array) # Get the mean of all elements in the array
ar_mean = array.mean() # Get the mean of all elements in the array, np.mean(array) does the same thing
print("np Array Mean:", ar_mean)


# Standard Deviation: np.std(array) or array.std()

# Get the standard deviation: square root of the average squared distance from the mean
arr_std = array.std()  # np.std(array) does the same thing
print("np Array Standard Deviation:", arr_std)

# Variance: np.var(array) or array.var()
arr_var = array.var() # Get the variance: the average of the squared differences from the mean
print("np Array Variance:", arr_var)


# Min value, Max value
arr_min_val = array.min()
arr_max_val = array.max()


print("np Array Min Value:", arr_min_val)
print("np Array Max Value:", arr_max_val)


# Argmin, Argmax: np.argmin(array) or array.argmin(), np.argmax(array) or array.argmax()

arr_argmin = array.argmin() # Get the index of the minimum value in the array
arr_argmax = array.argmax() # Get the index of the maximum value in the array

print("np Array Argmin:", arr_argmin, "Of Value", arr_min_val)
print("np Array Argmax:", arr_argmax, "Of Value", arr_max_val)

np Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
np Array Sum 45
np Array Sum along axis 0(columns): [12 15 18]
np Array Sum along axis 1(rows): [ 6 15 24]
np Array Mean: 5.0
np Array Standard Deviation: 2.581988897471611
np Array Variance: 6.666666666666667
np Array Min Value: 1
np Array Max Value: 9
np Array Argmin: 0 Of Value 1
np Array Argmax: 8 Of Value 9


In [196]:
# Aggreation function with axis and slices

print("np Array\n", array)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]


# Sum

arr_sum_axis0 = np.sum(array, axis=0) # Get the sum of all elements in the array along axis 0 (columns)
arr_sum_axis1 = np.sum(array, axis=1) # Get the sum of all elements in the array along axis 1 (rows)

print("np Array Sum along axis 0(columns):", arr_sum_axis0)
print("np Array Sum along axis 1(rows):", arr_sum_axis1, "\n")


arr_sum_slice = np.sum(array[1:3, 1:3]) # Get the sum of all elements in the array slice [1:3, 1:3]

print("np Array of slice [1:3, 1:3]:\n", array[1:3, 1:3])
print("np Array Sum of slice [1:3, 1:3]:", arr_sum_slice, "\n")



# Mean

arr_mean_axis0 = np.mean(array, axis=0) # Get the mean of all elements in the array along axis 0 (columns)
arr_mean_axis1 = np.mean(array, axis=1) # Get the mean of all elements in the array along axis 1 (rows)


print("np Array Mean along axis 0(columns):", arr_mean_axis0)
print("np Array Mean along axis 1(rows):", arr_mean_axis1, "\n")


arr_mean_slice = np.mean(array[1:3, 1:3]) # Get the mean of all elements in the array slice [1:3, 1:3]

print("np Array of slice [1:3, 1:3]\n ", array[1:3, 1:3])
print("np Array Mean of slice [1:3, 1:3]:", arr_mean_slice, "\n")


# Standard Deviation

arr_std_axis0 = np.std(array, axis=0) # Get the standard deviation of all elements in the array along axis 0 (columns)
arr_std_axis1 = np.std(array, axis=1) # Get the standard deviation of all elements in the array along axis 1 (rows)

print("np Array Standard Deviation along axis 0(columns):", arr_std_axis0)
print("np Array Standard Deviation along axis 1(rows):", arr_std_axis1, "\n")

arr_std_slice = np.std(array[1:3, 1:3]) # Get the standard deviation of all elements in the array slice [1:3, 1:3]

print("np Array of slice [1:3, 1:3]\n ", array[1:3, 1:3])
print("np Array Standard Deviation of slice [1:3, 1:3]:", arr_std_slice, "\n")


# Variance

arr_var_axis0 = np.var(array, axis=0) # Get the variance of all elements in the array along axis 0 (columns)
arr_var_axis1 = np.var(array, axis=1) # Get the variance of all elements in the array along axis 1 (rows)

arr_var_slice = np.var(array[1:3, 1:3]) # Get the variance of all elements in the array slice [1:3, 1:3]

print("np Array of slice [1:3, 1:3]\n ", array[1:3, 1:3])
print("np Array Variance of slice [1:3, 1:3]:", arr_var_slice, "\n")

print("np Array Variance along axis 0(columns):", arr_var_axis0)
print("np Array Variance along axis 1(rows):", arr_var_axis1, "\n")

np Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
np Array Sum along axis 0(columns): [12 15 18]
np Array Sum along axis 1(rows): [ 6 15 24] 

np Array of slice [1:3, 1:3]:
 [[5 6]
 [8 9]]
np Array Sum of slice [1:3, 1:3]: 28 

np Array Mean along axis 0(columns): [4. 5. 6.]
np Array Mean along axis 1(rows): [2. 5. 8.] 

np Array of slice [1:3, 1:3]
  [[5 6]
 [8 9]]
np Array Mean of slice [1:3, 1:3]: 7.0 

np Array Standard Deviation along axis 0(columns): [2.44948974 2.44948974 2.44948974]
np Array Standard Deviation along axis 1(rows): [0.81649658 0.81649658 0.81649658] 

np Array of slice [1:3, 1:3]
  [[5 6]
 [8 9]]
np Array Standard Deviation of slice [1:3, 1:3]: 1.5811388300841898 

np Array of slice [1:3, 1:3]
  [[5 6]
 [8 9]]
np Array Variance of slice [1:3, 1:3]: 2.5 

np Array Variance along axis 0(columns): [6. 6. 6.]
np Array Variance along axis 1(rows): [0.66666667 0.66666667 0.66666667] 



In [197]:
# Get Mean, Median and Mode of 1D Numpy array
arr_weights = np.array([[1,4], [12,19], [5,2], [-3, 19], [7, 8], [9, 10], [11, 19], [15, 16], [17, 18], [19, 20]])

# Mean
arr_mean = np.mean(arr_weights) # Get the mean of all elements in the array


# Median
arr_median = np.median(arr_weights) # Get the median of all elements in the array


# Get the mode of all elements in the array, if the array has negative values use scipy.stats.mode() method 
if arr_weights.min() > -1 and np.issubdtype(arr_weights.dtype, np.integer):
    
    arr_counts = np.bincount(arr_weights.flatten()) # Get the mode of all elements in the array
    
    arr_mode = arr_counts.argmax() # Get the mode of all elements in the array
    arr_mode_count = arr_counts[arr_mode] # Get the count of the mode of all elements in the array
else:
    unique_vals, return_counts = np.unique(arr_weights, return_counts=True) # Get the unique values and their counts
    print("Unique vals and count: ", unique_vals, return_counts)
    # arr_mode = unique_vals[np.argmax(return_counts)] # Get the mode of all elements in the array

    # or with scipy
    arr_mode, arr_mode_count = st.mode(arr_weights, axis=None) # use `.count` gets how many times it appeared
    # Or 
    # arr_mode = st.mode(arr_weights, keepdims=True).mode[0]

print("np Array\n", arr_weights)
print("np Array Mean:", arr_mean)
print("np Array Median:", arr_median)
print("np Array Mode:", arr_mode, "with count:", arr_mode_count)

Unique vals and count:  [-3  1  2  4  5  7  8  9 10 11 12 15 16 17 18 19 20] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 4 1]
np Array
 [[ 1  4]
 [12 19]
 [ 5  2]
 [-3 19]
 [ 7  8]
 [ 9 10]
 [11 19]
 [15 16]
 [17 18]
 [19 20]]
np Array Mean: 11.4
np Array Median: 11.5
np Array Mode: 19 with count: 4


In [198]:
# Filtering with Numpy, get the teenagers, adults and seniors from the array of ages

arr_ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65, 19, 12], 
                                              [39, 22, 15, 99, 18, 19, 20, 21, 19, 20]])

arr_teenagers = np.sort(arr_ages[arr_ages < 18])

arr_adult = np.sort(arr_ages[ (18 <= arr_ages) & (arr_ages < 65) ])

arr_adult_unique, arr_adult_unique_count = np.unique(arr_adult, return_counts=True) # Get the unique values and their counts

arr_senior = np.sort(arr_ages[arr_ages >= 65])


arr_under_18_over_65 = np.sort(arr_ages[(18 > arr_ages) | (arr_ages >= 65)])


arr_even_ages = arr_ages[arr_ages % 2 == 0]

arr_odd_ages = arr_ages[arr_ages % 2 != 0]

print("np Array\n", arr_ages)
print("Teenagers:", arr_teenagers)
print("Adults (Unique):", arr_adult_unique, "with count:", arr_adult_unique_count, "and mode", arr_adult_unique[arr_adult_unique_count.argmax()])
print("Adults:", arr_adult)
print("Seniors:", arr_senior)
print("Less than 18 or greater than 65:", arr_under_18_over_65)

print("Even Ages:", arr_even_ages)
print("Odd Ages:", arr_odd_ages)

# Where, slower than indexing but preserve the original shape of the array, and can be used to replace values in the array

# Get the adults ages, if not adult age, replace with 0, -1 or np.nan, np.nan is better because it is not a number 
# and can be easily filtered out later
adults = np.where((arr_ages >= 18) & (arr_ages < 65)  , arr_ages, np.nan) 

print("Adults (Using Where):", adults)
print("Adults (Using Where) without NaN:", np.sort(adults[~np.isnan(adults)]).reshape(7, 2)) # Filter out the NaN values

np Array
 [[21 17 19 20 16 30 18 65 19 12]
 [39 22 15 99 18 19 20 21 19 20]]
Teenagers: [12 15 16 17]
Adults (Unique): [18 19 20 21 22 30 39] with count: [2 4 3 2 1 1 1] and mode 19
Adults: [18 18 19 19 19 19 20 20 20 21 21 22 30 39]
Seniors: [65 99]
Less than 18 or greater than 65: [12 15 16 17 65 99]
Even Ages: [20 16 30 18 12 22 18 20 20]
Odd Ages: [21 17 19 65 19 39 15 99 19 21 19]
Adults (Using Where): [[21. nan 19. 20. nan 30. 18. nan 19. nan]
 [39. 22. nan nan 18. 19. 20. 21. 19. 20.]]
Adults (Using Where) without NaN: [[18. 18.]
 [19. 19.]
 [19. 19.]
 [20. 20.]
 [20. 21.]
 [21. 22.]
 [30. 39.]]


### Random Numbers

In [199]:

# Random Number Generation
random_num_inclusive = rnd.randint(1, 10) # 1 to 10 Inclusive
random_num_exclusive = rnd.randrange(1, 10) # 1 to 9 Exclusive
random_num_random = rnd.random() # 0 to 1 Exclusive

random_float_inclusive = rnd.uniform(1, 10) # 1 to 10 Inclusive

print(f"Random Number Inclusive(1-10): {random_num_inclusive}")
print(f"Random Number Exclusive(1-10): {random_num_exclusive}")
print(f"Random Number Random Exclusive(0-1): {random_num_random}")
print(f"Random Float Inclusive(1-10): {random_float_inclusive}")

# Random selection

fruit_list: list[str] = ["apple", "banana", "cherry", "kiwi", "grapes", "orange", "mango", "pear", "peach", "plum"]

random_fruit_selection = rnd.choice(fruit_list) # Randomly select one fruit from the list

random_fruit_selection_mutiple_4 = rnd.sample(fruit_list, 4)

print(f"Fruit List: {fruit_list}")
print(f"Random Fruit Selection: {random_fruit_selection}")
print(f"Random Fruit Selection Multiple 4: {random_fruit_selection_mutiple_4}")

# Shuffle 

fruit_list_shuffle = rnd.shuffle(fruit_list) # Shuffle the list in place
print(f"Fruit List Shuffle: {fruit_list}")


# Secrets module for cryptographically secure random numbers, better than random module for security purposes


# By default its from 0 to n-1, incusive, so we add 1 to make it inclusive of n
random_secure_num_inclusive = secrets.randbelow(10) + 1 # 1 to 10 Inclusive

print(f"Random Secure Number Inclusive(1-10): {random_secure_num_inclusive}")

random_bits_inclusive = secrets.randbits(4) # 0 to 15 Inclusive, 4 bits can represent 0 to 15 (2**4 - 1 = 15)

print(f"Random Bits Inclusive(0-15): {random_bits_inclusive}")



Random Number Inclusive(1-10): 4
Random Number Exclusive(1-10): 5
Random Number Random Exclusive(0-1): 0.41087836202008177
Random Float Inclusive(1-10): 6.218641268351862
Fruit List: ['apple', 'banana', 'cherry', 'kiwi', 'grapes', 'orange', 'mango', 'pear', 'peach', 'plum']
Random Fruit Selection: grapes
Random Fruit Selection Multiple 4: ['grapes', 'peach', 'plum', 'banana']
Fruit List Shuffle: ['apple', 'orange', 'banana', 'mango', 'cherry', 'plum', 'pear', 'grapes', 'kiwi', 'peach']
Random Secure Number Inclusive(1-10): 9
Random Bits Inclusive(0-15): 12


## Random Numbers in Numpy

In [ ]:
# Random number Generator

print("Integers with random seed")

rng = np.random.default_rng() # Create a random number generator, if no seed is provided, 
                                         # it will use the current time as the seed, 
                                         # so it will be different every time you run the code

# Ingeters

np_random_int_inclusive = rng.integers(1, 6, size=1, endpoint=True)
np_random_int_exclusive = rng.integers(1, 7, size=1) 

np_random_int_exclusive_2d = rng.integers(1, 7, size=(3,3))

np_randint_exclusive = np.random.randint(1, 10, size=1)
np_randint_exclusive_2d = np.random.randint(1, 10, size=(5,3))


print(f"Random Integer Inclusive(1-6): {np_random_int_inclusive}")
print(f"Random Integer Exclusive(1-6): {np_random_int_exclusive}")
print(f"Random Integer Exclusive 2D(1-6): {np_random_int_exclusive_2d}")

print(f"Random Integer(randint) Exclusive(1-6): {np_randint_exclusive}")
print(f"Random Integer(randint) Exclusive 2D(1-6): {np_randint_exclusive_2d}")
print()

# Get the same random numbers every time you run the code, 
# because we provided a seed value of 10

print("Integers with specific seed")

rng = np.random.default_rng(seed=10) 


# Ingeters

np_random_int_inclusive = rng.integers(1, 6, size=1, endpoint=True)
np_random_int_exclusive = rng.integers(1, 7, size=1) 

np_random_int_exclusive_2d = rng.integers(1, 7, size=(3,3))

print(f"Random Integer Inclusive(1-6): \n{np_random_int_inclusive}")
print(f"Random Integer Exclusive(1-6): \n{np_random_int_exclusive}")
print(f"Random Integer Exclusive 2D(1-6): \n{np_random_int_exclusive_2d}")
print()

# Floating point numbers

# np.random.seed(seed=2) # Keep the seed same 


print(f"Random Floating numbers within 0-1\n", np.random.uniform())
print(f"Random Floating numbers with range 0 to 10\n", np.random.uniform(1, 10))
print(f"Random Floating numbers with range 0 to 10 of size 6\n", np.random.uniform(1, 10, size=6))
print()

# Shuffle an arrray

rng = np.random.default_rng()

array = np.array([1, 2, 3, 4, 5])

print("Array", array)

rng.shuffle(array)

print("Shuffle Array",array)


# Random choice

choice = rng.choice(array) 
# choices = rng.choice(array, size= 3) 
choices = rng.choice(array, size= (2, 10)) 
print("Random Choice from array", choice)
print("Random Choices from array\n", choices)


fruit_emo_array = np.array(["🍎", "🍊", "🍉", "🥝"])

random_fruits = rng.choice(fruit_emo_array, size=(3, 3)) 

print(random_fruits)

is_found = False


for fruit in fruit_emo_array:
    if not is_found:
        for idx in range(0, 3):
            if np.all(random_fruits[idx] == str(fruit)): 
                print("You won", fruit)
                break
        else:
            continue
        break

Integers with random seed
Random Integer Inclusive(1-6): [5]
Random Integer Exclusive(1-6): [5]
Random Integer Exclusive 2D(1-6): [[4 5 5]
 [3 6 1]
 [6 5 5]]
Random Integer(randint) Exclusive(1-6): [7]
Random Integer(randint) Exclusive 2D(1-6): [[7 6 8]
 [7 8 1]
 [4 5 7]
 [6 4 1]
 [6 3 2]]

Integers with specific seed
Random Integer Inclusive(1-6): 
[5]
Random Integer Exclusive(1-6): 
[6]
Random Integer Exclusive 2D(1-6): 
[[2 2 5]
 [5 4 1]
 [5 4 1]]

Random Floating numbers within 0-1
 0.6507598224519917
Random Floating numbers with range 0 to 10
 6.472319651541491
Random Floating numbers with range 0 to 10 of size 6
 [3.32214662 6.87379309 9.12710709 1.39539196 8.90836002 2.82295702]

Array [1 2 3 4 5]
Shuffle Array [5 3 4 1 2]
Random Choice from array 4
Random Choices from array
 [[3 4 5 2 1 3 1 1 3 2]
 [4 1 5 2 4 2 5 3 3 3]]
[['🍉' '🍉' '🍊']
 ['🍎' '🍊' '🍊']
 ['🍊' '🍉' '🍊']]


### More Numpy Exercises

In [ ]:
# Python List and Numpy Array: .arange(), .reshape(), .ndim, .shape, time took to create large lists/array


size : int = 1_000_000
python_list : list[int] = list(range(size))
numpy_array  = np.arange(size)

print("Python list size:", len(python_list))
print("Numpy Array size:", numpy_array.size, "and shape", numpy_array.shape)

# Reshaping numpy_array 

numpy_array = np.arange(size).reshape(250_000, 4)
print("Numpy Array size:", numpy_array.size, "and shape", numpy_array.shape, "and N-dimensions", numpy_array.ndim)

# Adding 10 in python_list and numpy_array with time
start : float  = time.time()
result_python_list = [num + 2 for num in python_list] # Loop required
python_list_time : float = time.time() - start

start : float = time.time()
result_numpy_time =  numpy_array + 2 # Vectorized
numpy_array_time : float = time.time() - start


print(f"Python List took {python_list_time:.6f} Secs to add 2 to the list(loop)")
print(f"Numpy Array took {numpy_array_time:.6f} Secs to add 2 to the array(vectorized)")

print(f"Differnce: {python_list_time/numpy_array_time:.1f}x Faster")


Python list size: 1000000
Numpy Array size: 1000000 and shape (1000000,)
Numpy Array size: 1000000 and shape (250000, 4) and N-dimensions 2
Python List took 0.064341 Secs to add 2 to the list(loop)
Numpy Array took 0.002184 Secs to add 2 to the array(vectorized)
Differnce: 29.5x Faster


### Numpy arrays creation ways


In [ ]:
# 1. From python list

np_py = np.array([1, 2, 3, 4]) 
print(np_py, type(np_py))

# 2. Using .arange(), similar to python's range functionm.
# arange(num) by default starts from 0 to num (exclusive) with step 1

np_ar = np.arange(0, 100, 1) # Same as np.arange(100) Exclusive
print(np_ar, np_ar.ndim, np_ar.shape,"\n")

# We can reshape the array as well with .reshape
np_ar = np_ar.reshape((20, 5))
print(np_ar, np_ar.ndim, np_ar.shape, "\n")

# 3. Using .linspace(), evenly spaced numbers (floating point numbers)

np_ls = np.linspace(1, 100, 10, dtype=float ) # Takes start, stop, numbers, dtype, bydefault dtype=float
print(np_ls, np_ls.ndim, np_ls.shape, np_ls.dtype,"\n")


# 4. Using .zeros((shape)), .ones((shape)) and .full(shape, fill_value).
# Creating arrays of zeros, ones and from specific value

rng = np.random.default_rng()

np_ze = np.zeros((4, 5)) # By default its float64
np_on = np.ones((10, 2)) # By default its float64
np_sp = np.full((1, 2), 10, dtype=int) # By default its float64

print(np_ze, np_ze.ndim, np_ze.shape, np_ze.dtype, "\n")
print(np_on, np_on.ndim, np_on.shape, np_on.dtype, "\n")
print(np_sp, np_sp.ndim, np_sp.shape, np_sp.dtype, "\n")

# 5. Using random.randint() and other random functions, by default type is float

np_ra =  np.random.randint(1, 10, size=(1,2)) # Legacy
np_ra = rng.integers(1, 10, size=(1,2)) # Modern approach


np_un = np.random.rand(10).reshape((5,2)) # Legacy,  Uniform distribution
np_un = rng.uniform(0, 1, size=(5,2)) # Same as .rand(), by default its low = 0.0 & high = 1.0

print(np_ra)
print(np_un)

# 6 Using .eye(N, M, k) identity matrics, ALone N is rows, M is columns, k is offset (-1, 0, 1..) 

# Same as np.eye(4), where N is rows, K is columns(Optional), k is offet (Optional)
# dtype=bool for True and Ffalse, same with dtype=int for int instead of float, default is float64
np_ey = np.eye(4, 4, k= 0, dtype=float) 

print("Identify matrix of  1, 10 with k=4:\n", np_ey,"\n")
print(np_ey.ndim, np_ey.shape, np_ey.dtype)


[1 2 3 4] <class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] 1 (100,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]] 2 (20, 5) 

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.] 1 (10,) float64 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 2 (4, 5) float64 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 2 (10, 2) float64 

[[1

 ### Numpy Types (dtype)

 Numpy Array are homogenous - all elements have the same type, Type affect memory usage and operation.

In [232]:
# Type inference and common types

np1 = np.array([1, 2, 3, 4])
np2 = np.array([1., 2, 3])
np3 = np.array([1, 2.3, 3]) # Mixed-Type: promoted to float
np4 = np.array([True, False, True])

# We can use .astype(int) or dtype=int for eg to change type 
# Example:
# np0 = np.array([1, 2.3, 3], dtype=np.int32) # np0.dtype # int64

print("Integer:", np1.dtype)
print("Integer:", np2.dtype)
print("Integer:", np3.dtype)
print("Integer:", np4.dtype)

# Specifying types

npf32 = np.array([1.2, 3.4, 3], dtype= np.float32)
npf64 = np1.astype(np.float64)

print("f32", npf32.dtype )
print("f64", npf64.dtype )

# Common types: int32, int64, float32, float64, bool
print("Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element")

Integer: int64
Integer: float64
Integer: float64
Integer: bool
f32 float32
f64 float64
Memory: int32/float32 = 4 bytes, int64/float64 = 8 bytes per element


### Numpy Array Attributes

In [233]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Array:")
print(arr)
print(f"\nShape: {arr.shape}")  # Dimensions of the array
print(f"Size: {arr.size}")  # Total number of elements
print(f"ndim: {arr.ndim}")  # Number of dimensions
print(f"dtype: {arr.dtype}")  # Data type
print(f"itemsize: {arr.itemsize} bytes")  # Size of each element
print(f"nbytes: {arr.nbytes} bytes")  # Total memory used
print(f"T (transpose):\n{arr.T}")  # Transpose of the array

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape: (3, 4)
Size: 12
ndim: 2
dtype: int64
itemsize: 8 bytes
nbytes: 96 bytes
T (transpose):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Array Manupulation: Reshaping and Resizing

In [ ]:
arr = np.arange(12)
print("Original Array:", arr,"\nShape:",arr.shape)

# Reshape - Change view, don't copy data
reshaped_arr = arr.reshape(3, 4)
print("\nReshaped Array:\n", reshaped_arr)
print("\nShape:", reshaped_arr.shape)

# Flatten - Convert to 1D
flatten_arr = arr.flatten()
print("\nFlatten Array:\n", flatten_arr)
print("\nShape:", flatten_arr.shape)


# Reshape with -1 (auto-calculate dimension)
auto_reshaped_arr = arr.reshape(2, -1) # -1 means "calculate automatically"
print("\nAuto Reshaped Array - (2, -1):\n", auto_reshaped_arr)
print("\nShape:", auto_reshaped_arr.shape)


# Transpose 
matrix = np.array([[1,2,3], [4, 5, 6]])
transpose_matrix = matrix.transpose() # or .T

print("\nOriginal Matrix:\n", matrix)
print("\nTranspose Matrix:\n", transpose_matrix)

# Concatenation
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5, 6], [7, 8]])

arr_vstack = np.vstack((arr1, arr2))
arr_hstack = np.hstack((arr1, arr2))

arr_concatenate_0 = np.concatenate((arr1, arr2), axis=0) # axis=0 Vertical Concatenate, Same as np.vstack()
arr_concatenate_1 = np.concatenate((arr1, arr2), axis=1) # axis= 1Horizontal Concatenate, Same as np.hstack() 


print("Concatenation")
print("\nArray 1:\n", arr1)
print("\nArray 2:\n", arr2)

print("Vertical Concatenation (.vstack())")
print("\n",arr_vstack)

print("Horizontal Concatenation (.hstack())")
print("\n",arr_hstack)

print("Using .concatenate(a,b)")
print("Axis=0 (Vertical): ")
print("\n",arr_concatenate_0)
print("Axis=1: (Horizontal) ")
print("\n",arr_concatenate_1)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11] 
Shape: (12,)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Shape: (3, 4)

Flatten Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Shape: (12,)

Auto Reshaped Array - (2, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Shape: (2, 6)

Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Concatenation

Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5 6]
 [7 8]]
Vertical Concatenation (.vstack())

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation (.hstack())

 [[1 2 5 6]
 [3 4 7 8]]
Using .concatenate(a,b)
Axis=0 (Vertical): 

 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Axis=1: (Horizontal) 

 [[1 2 5 6]
 [3 4 7 8]]


 Understanding Dimensions and Axis

**Key Concepts:**
- **Dimension (ndim)**: Number of axes (1D=1, 2D=2, 3D=3)
- **Axis**: The dimension along which an operation is performed (starts at 0)
- **Shape**: Size of each dimension (e.g., (3, 4) = 3 rows, 4 columns)
- **For 2D arrays**: `axis=0` = rows (vertical), `axis=1` = columns (horizontal)

In [251]:
# Understanding dimensions
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("1D Array:")
print(f"  {arr_1d} → shape: {arr_1d.shape}, ndim: {arr_1d.ndim} (axis 0 only)\n")

print("2D Array:")
print(f"  {arr_2d}")
print(f"  shape: {arr_2d.shape} (rows, columns)")
print(f"  ndim: {arr_2d.ndim} (axis 0=rows, axis 1=columns)")

# Axis in operations: specifies which dimension to collapse
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}\n")

# axis=0: collapse rows (operate down columns) → one value per column
sum_axis0 = np.sum(matrix, axis=0)
print(f"axis=0 (down rows): {sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: Column 0 sum = {matrix[0,0]} + {matrix[1,0]} + {matrix[2,0]} = {sum_axis0[0]}\n")

# axis=1: collapse columns (operate across rows) → one value per row
sum_axis1 = np.sum(matrix, axis=1)
print(f"axis=1 (across columns): {sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: Row 0 sum = {matrix[0,0]} + {matrix[0,1]} + {matrix[0,2]} = {sum_axis1[0]}\n")

1D Array:
  [1 2 3 4 5] → shape: (5,), ndim: 1 (axis 0 only)

2D Array:
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
  shape: (3, 3) (rows, columns)
  ndim: 2 (axis 0=rows, axis 1=columns)
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

axis=0 (down rows): [12 15 18]  → shape: (3,)
  Example: Column 0 sum = 1 + 4 + 7 = 12

axis=1 (across columns): [ 6 15 24]  → shape: (3,)
  Example: Row 0 sum = 1 + 2 + 3 = 6



In [252]:
# 3D Arrays: Axis with more than 2 dimensions
# Think: (depth, rows, columns) or (samples, height, width)
arr_3d = np.array([
    [[1, 2, 3],    # First 2D slice (page 0)
     [4, 5, 6]],
    [[7, 8, 9],    # Second 2D slice (page 1)
     [10, 11, 12]]
])

print("3D Array (shape: 2x2x3):")
print("Think: 2 pages, each with a 2x3 matrix")
print(arr_3d)
print(f"Shape: {arr_3d.shape}  (depth=2, rows=2, columns=3)\n")

# axis=0: collapse depth (across pages) → result: 2D (2×3)
sum_axis0 = np.sum(arr_3d, axis=0)
print(f"axis=0 (across pages):\n{sum_axis0}  → shape: {sum_axis0.shape}")
print(f"  Example: [0,0,0] = {arr_3d[0,0,0]} + {arr_3d[1,0,0]} = {sum_axis0[0,0]}\n")

# axis=1: collapse rows (down each page) → result: 2D (2×3)
sum_axis1 = np.sum(arr_3d, axis=1)
print(f"axis=1 (down rows):\n{sum_axis1}  → shape: {sum_axis1.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,1,0]} = {sum_axis1[0,0]}\n")

# axis=2: collapse columns (across each row) → result: 2D (2×2)
sum_axis2 = np.sum(arr_3d, axis=2)
print(f"axis=2 (across columns):\n{sum_axis2}  → shape: {sum_axis2.shape}")
print(f"  Example: [0,0] = {arr_3d[0,0,0]} + {arr_3d[0,0,1]} + {arr_3d[0,0,2]} = {sum_axis2[0,0]}\n")


3D Array (shape: 2x2x3):
Think: 2 pages, each with a 2x3 matrix
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)  (depth=2, rows=2, columns=3)

axis=0 (across pages):
[[ 8 10 12]
 [14 16 18]]  → shape: (2, 3)
  Example: [0,0,0] = 1 + 7 = 8

axis=1 (down rows):
[[ 5  7  9]
 [17 19 21]]  → shape: (2, 3)
  Example: [0,0] = 1 + 4 = 5

axis=2 (across columns):
[[ 6 15]
 [24 33]]  → shape: (2, 2)
  Example: [0,0] = 1 + 2 + 3 = 6



 ### Statistical Operations

In [253]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Array:", arr)

# Basic statistics
print(f"\n--- Basic Statistics ---")
print(f"Sum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")
print(f"Variance: {np.var(arr)}")
print(f"Min: {np.min(arr)}")
print(f"Max: {np.max(arr)}")
print(f"Index of min: {np.argmin(arr)}")
print(f"Index of max: {np.argmax(arr)}")

# 2D array statistics (with axis parameter)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n--- 2D Array Statistics ---")
print("Matrix:")
print(matrix)
print(f"Sum of all elements: {np.sum(matrix)}")
print(f"Sum along rows (axis=0): {np.sum(matrix, axis=0)}")  # Column sums
print(f"Sum along columns (axis=1): {np.sum(matrix, axis=1)}")  # Row sums
print(f"Mean of each column: {np.mean(matrix, axis=0)}")
print(f"Mean of each row: {np.mean(matrix, axis=1)}")


Array: [ 1  2  3  4  5  6  7  8  9 10]

--- Basic Statistics ---
Sum: 55
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Index of min: 0
Index of max: 9

--- 2D Array Statistics ---
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements: 45
Sum along rows (axis=0): [12 15 18]
Sum along columns (axis=1): [ 6 15 24]
Mean of each column: [4. 5. 6.]
Mean of each row: [2. 5. 8.]


### Linear Algebra Operations

In [ ]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix a:")
print(a)
print("\nMatrix b:")
print(b)

# Element-wise multiplication (NOT matrix multiplication)
print("\nElement-wise multiplication (a * b):")
print(a * b)

# Dot product of vectors
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(f"\nDot product of vectors {v1} and {v2}: {np.dot(v1, v2)}")

# Matrix properties
matrix = np.array([[1, 2], [3, 4]])
print("\n--- Matrix Properties ---")
print("Matrix:")
print(matrix)
print(f"Determinant: {np.linalg.det(matrix)}")
print(f"Inverse:")
print(np.linalg.inv(matrix))
print(f"Transpose:")
print(matrix.T)

# Eigenvalues and eigenvectors
# Eigenvalues and eigenvectors are special numbers and vectors associated with linear transformations and square matrices. 
# When a matrix multiplies an eigenvector, 
# the resulting vector points in the exact same direction, scaled only by a factor equal to the eigenvalue. 
# The core equation is Av = λ v


eigenvals, eigenvecs = np.linalg.eig(matrix)
print(f"\nEigenvalues: {eigenvals}")
print(f"Eigenvectors:\n{eigenvecs}")

Matrix a:
[[1 2]
 [3 4]]

Matrix b:
[[5 6]
 [7 8]]

Element-wise multiplication (a * b):
[[ 5 12]
 [21 32]]

Dot product of vectors [1 2 3] and [4 5 6]: 32

--- Matrix Properties ---
Matrix:
[[1 2]
 [3 4]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Transpose:
[[1 3]
 [2 4]]

Eigenvalues: [-0.37228132+0.j  5.37228132+0.j]
Eigenvectors:
[[-0.82456484+0.j -0.41597356+0.j]
 [ 0.56576746+0.j -0.90937671+0.j]]
