### Numpy

In [1]:

import string

import numpy as np

print(f"numpy(np {np.__version__} is imported")


numpy(np 2.5.1 is imported


In [2]:
# Regular list

""" 
Apple = 1
Orange = 2
Grapes = 3
Kiwi = 4
"""

fruit_list : list[int] = [1,2,3,4]

double_fruit_list: list[int] = fruit_list *2;

print(fruit_list)

print(double_fruit_list)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [3]:
# Numpy array, faster than regular python list.

np_fruit_array = np.array(fruit_list)

multiplied_np_fruit_array = np_fruit_array * 2;

print(f"Numpy array\t\t {np_fruit_array} of type {type(np_fruit_array)}")
print(f"Multiplied Numpy array   {multiplied_np_fruit_array} of type {type(multiplied_np_fruit_array)}")


Numpy array		 [1 2 3 4] of type <class 'numpy.ndarray'>
Multiplied Numpy array   [2 4 6 8] of type <class 'numpy.ndarray'>


#### 1D, 2D and 3D Array Dimensions

![1_3D_array](https://i0.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)

In [4]:
# Multi Dimensional Numpy Array


array_0d = np.array(1)

print(array_0d, f"of type {type(array_0d)} having {array_0d.ndim} Dimensions\n")


array_1d = np.array([1, 2, 3])

print(array_1d, f"of type {type(array_1d)} having {array_1d.ndim} Dimensions\n")


array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d, f"of type {type(array_2d)} having {array_2d.ndim} Dimensions\n")


1 of type <class 'numpy.ndarray'> having 0 Dimensions

[1 2 3] of type <class 'numpy.ndarray'> having 1 Dimensions

[[1 2 3]
 [4 5 6]
 [7 8 9]] of type <class 'numpy.ndarray'> having 2 Dimensions



In [5]:
# Acesss array elements in 2D Numpy Arrray

print(array_2d, "\n")

print(f"Shaped of 2d Array {array_2d.shape}")

array_2d_first_row = array_2d[0]

print(f"First Row {array_2d_first_row}")

array_2d_first_col = array_2d[:, 0]

print(f"First Coloumn {array_2d_first_col}")

array_2d_first_element = array_2d[0][1]

print(f"First element {array_2d_first_element}")

array_2d_last_element = array_2d[-1][-1]

print(f"Last element {array_2d_last_element}")

array_2d_second_third_row = array_2d[1:]

print(f"Second-Third Row \n{array_2d_second_third_row}\n")

array_2d_last_row = array_2d[-1]  # array_2d[-1:] 

print("Last Row", array_2d_last_row)

array_2d_last_col = array_2d[ :, -1]

print("Last Col", array_2d_last_col)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Shaped of 2d Array (3, 3)
First Row [1 2 3]
First Coloumn [1 4 7]
First element 2
Last element 9
Second-Third Row 
[[4 5 6]
 [7 8 9]]

Last Row [7 8 9]
Last Col [3 6 9]


In [6]:
# 3d and 4d array

array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

print(array_3d, f"{array_3d.ndim}D", f"Shape {array_3d.shape}", sep="\t")

array_4d = np.array([[
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]], 

                                              [[[1, 2, 3],[4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]],

                                              [[[1, 2,3], [4, 5, 6], [7, 8, 9]],
                                              [[9, 8, 7], [6, 5, 4], [3, 2, 1]],
                                              [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
                                              ])

print(array_4d, f"{array_4d.ndim}D",f"Shape {array_4d.shape}" , sep="\t",)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]	3D	Shape (3, 3, 3)
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]	4D	Shape (3, 3, 3, 3)


In [7]:
## Access Elements from 3d Array

print(array_3d, "\n")

array_3d_first_layer = array_3d[0]

print(f"First Layer: \n{array_3d_first_layer}\n")

array_3d_last_layer = array_3d[-1]

print(f"Last Layer: \n{array_3d_last_layer}\n")

array_3d_second_third_layers = array_3d[1:]

print(f"Second-Third Layers: \n{array_3d_second_third_layers}\n")

array_3d_first_layer_second_row = array_3d[0][1] # Or array_3d[0, 1]

print(f"First Layer Second Row {array_3d_first_layer_second_row}")

array_3d_second_layer_last_col = array_3d[1, :, -1] 

print(f"Second Layer Last Col, {array_3d_second_layer_last_col}")


num_891_from_array_3d: int = int(str(array_3d[0, 2, 1]) + str(array_3d[1, 0, 0]) + str(array_3d[2, 0, 0 ]))

print(f"{num_891_from_array_3d}")




[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]] 

First Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Last Layer: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Second-Third Layers: 
[[[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]

First Layer Second Row [4 5 6]
Second Layer Last Col, [7 4 1]
891


In [8]:
# Slicing with Numpy, note all the slices are just view to the actual array, if you want independent
# array use .copy() method eg. my_array.copy() or my_array[:].copy() or my_array.T.copy() for transponse matric

my_array = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10 , 11, 12], 
    [13, 14, 15, 16 ]
]) # Shape (4, 4)

print("My Array:\n", my_array, "\n")


my_array_half_slice = my_array[:2, :]

print(f"First Half Slice: \n{my_array_half_slice}\n")

my_array_other_half_slice = my_array[2:,: ]

print(f"Other Half Slice: \n{my_array_other_half_slice}\n")

my_array_first_row  = my_array[-1]

print(f"First Row: \n{my_array_first_row}\n")

my_array_second_row_third_fourth_element_slice = my_array[1, 2:] 

print(f"Third & fourth Element from second row: {my_array_second_row_third_fourth_element_slice}")

my_array_reverse_first_row = my_array[0][::-1]

print(f"First row reversed {my_array_reverse_first_row}")

my_array_same_row_order_reverse_elements  = my_array[:, ::-1]

print(f"Rows with reversed elements\n{my_array_same_row_order_reverse_elements}")

my_array_alternate_rows = my_array[::2]

print("Alternating rows\n", my_array_alternate_rows)

my_array_second_col = my_array[:, 1]

print("Second Row\n", my_array_second_col)


My Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

First Half Slice: 
[[1 2 3 4]
 [5 6 7 8]]

Other Half Slice: 
[[ 9 10 11 12]
 [13 14 15 16]]

First Row: 
[13 14 15 16]

Third & fourth Element from second row: [7 8]
First row reversed [4 3 2 1]
Rows with reversed elements
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Alternating rows
 [[ 1  2  3  4]
 [ 9 10 11 12]]
Second Row
 [ 2  6 10 14]


In [9]:
# More slicing operations

print(my_array)

# Stepping
my_array_in_between_elements_in_rows = my_array[:, ::2]

print("Alternation elements in the rows:\n", my_array_in_between_elements_in_rows)

my_array_transpose = my_array.T

print("Transpose of my_array\n", my_array_transpose)

my_array_second_to_fourth_cols_transpose = my_array[:, 0:4].transpose() # or T or np.transponse(my_array_second_to_fourth_cols)

print("Second-Fourth Cols in the array\n", my_array_second_to_fourth_cols_transpose)


my_array_1_4_col = my_array[:, [0, 3]]

print("First and fourth col\n", my_array_1_4_col)

first_two_rows_first_two_cols = my_array[:2, :2]

print("First two rows and firt two cols:\n",first_two_rows_first_two_cols )

first_two_rows_last_two_cols = my_array[:2, 2:]

print("First two rows and last two cols:\n",first_two_rows_last_two_cols )

last_two_rows_first_two_cols = my_array[2:, :2]

print("Last two rows, first two cols\n", last_two_rows_first_two_cols, "Last two rows, last two cols\n", my_array[2:, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Alternation elements in the rows:
 [[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
Transpose of my_array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Second-Fourth Cols in the array
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
First and fourth col
 [[ 1  4]
 [ 5  8]
 [ 9 12]
 [13 16]]
First two rows and firt two cols:
 [[1 2]
 [5 6]]
First two rows and last two cols:
 [[3 4]
 [7 8]]
Last two rows, first two cols
 [[ 9 10]
 [13 14]] Last two rows, last two cols
 [[11 12]
 [15 16]]


In [10]:

letters = string.ascii_lowercase

my_letters = np.append(list(letters), "_").reshape(3, 3,3)

print(my_letters)

sun : str = my_letters[2][0][0]  + my_letters[2][0][2] + my_letters[1][1][1]

print(f"Sol from espanol is {sun} in English")

[[['a' 'b' 'c']
  ['d' 'e' 'f']
  ['g' 'h' 'i']]

 [['j' 'k' 'l']
  ['m' 'n' 'o']
  ['p' 'q' 'r']]

 [['s' 't' 'u']
  ['v' 'w' 'x']
  ['y' 'z' '_']]]
Sol from espanol is sun in English


### Scaler Arithemetic in Numy

In [11]:
my_array = np.array([1, 2, 3])

print(my_array, "\n")

print("+  2 ", my_array + 2)
print("-  4",my_array - 4)
print("/  3",my_array / 3)
print("%  2",my_array % 2)
print("** 2",my_array ** 2)

[1 2 3] 

+  2  [3 4 5]
-  4 [-3 -2 -1]
/  3 [0.33333333 0.66666667 1.        ]
%  2 [1 0 1]
** 2 [1 4 9]


### Vector Math Functions in Numpy 

In [12]:
print(my_array)

print("Transponse:\t", np.transpose(my_array)) # Or my_array.T or my_array.transpose()

print("Square root:\t", np.sqrt(my_array))

print("Pi value:\t", np.pi)

print("Round value:\t", np.round(my_array)) # Or my_array.round()

print("Floor value", np.floor(my_array))

print("Ceil value:\t", np.ceil(my_array)) 

[1 2 3]
Transponse:	 [1 2 3]
Square root:	 [1.         1.41421356 1.73205081]
Pi value:	 3.141592653589793
Round value:	 [1 2 3]
Floor value [1 2 3]
Ceil value:	 [1 2 3]


In [13]:
# Calcualte the radius as the area of circle from np.array of radii

radii_array = np.array([1, 2, 3])
circle_radii_area_array = np.pi * radii_array **2 

print(circle_radii_area_array)

[ 3.14159265 12.56637061 28.27433388]


### Comparsion operators in Numpy

In [14]:
students_scores = np.array([100, 70, 60, 23, 50, 80]) 
# students_marks: list[int] = [int(score) for score in students_scores]
students_marks: list[int]= students_scores.tolist()


print(students_marks)
print(students_scores)
print()

print(students_scores == 100 )
print([val == 100 for val in students_marks])
print()

# Sutdents, who score atleast 35, pass
print(students_scores >= 35) 
print([val >= 35  for val in students_marks])
print()


# Students, who score perfect 100, just get those student score
print(students_scores[students_scores == 100])
print([val for val in students_marks if val == 100])
print()

# Students, who score atleast 35, just get those student scores [Pass]
print(students_scores[students_scores >=35])
print([val for val in students_marks if val >=35 ])
print()

# Students, who score less than 35, just get those student scores [Fail] 
print(students_scores[students_scores<35])
print([val for val in students_marks if val <35])


[100, 70, 60, 23, 50, 80]
[100  70  60  23  50  80]

[ True False False False False False]
[True, False, False, False, False, False]

[ True  True  True False  True  True]
[True, True, True, False, True, True]

[100]
[100]

[100  70  60  50  80]
[100, 70, 60, 50, 80]

[23]
[23]


## Ways to create arrays with Numpy,Zeros, Ones, Reshape..

In [15]:
# Ones Array
ones_array = np.ones((3, 2, 4), dtype=int)
print(ones_array, "\n")

# Zeros Array

zeros_array = np.zeros((2, 3, 5),dtype=int)
print(zeros_array, "\n")

letters: list[str] = ["A", "Z", "D", "%", "C"]
my_letters = np.append(letters, values="W").reshape(2, 3)

print(my_letters)
print()

letters.append("W")
perfect_letters = np.array(letters).reshape(2, 3)

print(perfect_letters)

[[[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]]] 

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]] 

[['A' 'Z' 'D']
 ['%' 'C' 'W']]

[['A' 'Z' 'D']
 ['%' 'C' 'W']]


## Broadcasting in Numpy

Performs operations on arrays with different shapes by virtually expanding dimensions, so they match the larger array's shape.

The two array's demensions(shape) have the same size.

OR

One of the array's dimensions(shape) has a size of 1.

![img](../images/broadcasting_in_numpy.png)

In [39]:
# 2D Array

array_2d  = np.array([[1, 2, 3, 4]])

array_2d_1col = np.array([[1], [2], [3], [4]])

print(f"{array_2d}\nShape:{array_2d.shape}\n")

print(f"{array_2d_1col}\nShape:{array_2d_1col.shape}")

# This two arrays statisfy our second condition where neither one dimension need to be 1
# (`1`, 4) & (4, `1`) Shape

print(f"{array_2d * array_2d_1col}, Shape: {(array_2d * array_2d_1col).shape}\n") # This works, we expand the vi

[[1 2 3 4]]
Shape:(1, 4)

[[1]
 [2]
 [3]
 [4]]
Shape:(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]], Shape: (4, 4)



In [40]:
# Creating multiplication table with numpy broadcasting..

array_1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array_2 = np.array([[1],[2], [3], [4], [5], [6], [7], [8], [9], [10]])

table = array_1 * array_2

print(table,f"Shape: {table.shape}" "\n")

for num in range(10): 
    print(f"Table {num+1}: ", table[num])

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] Shape: (10, 10)

Table 1:  [ 1  2  3  4  5  6  7  8  9 10]
Table 2:  [ 2  4  6  8 10 12 14 16 18 20]
Table 3:  [ 3  6  9 12 15 18 21 24 27 30]
Table 4:  [ 4  8 12 16 20 24 28 32 36 40]
Table 5:  [ 5 10 15 20 25 30 35 40 45 50]
Table 6:  [ 6 12 18 24 30 36 42 48 54 60]
Table 7:  [ 7 14 21 28 35 42 49 56 63 70]
Table 8:  [ 8 16 24 32 40 48 56 64 72 80]
Table 9:  [ 9 18 27 36 45 54 63 72 81 90]
Table 10:  [ 10  20  30  40  50  60  70  80  90 100]


In [47]:
# Broadcasting with same dimensions(shape)

array_1 = np.array([[1, 2], [3, 4], [5, 6]])

print(array_1, f"Shape: {array_1.shape}")

array_2 = np.array([10, 20])

print("\n",array_2, f"Shape: {array_2.shape}")

#Broadcast to bigger array aka, array_1 (shape: 3,2 )

array_3 = array_1 * array_2

print("\n",array_3, f"Shape: {array_3.shape}")



[[1 2]
 [3 4]
 [5 6]] Shape: (3, 2)

 [10 20] Shape: (2,)

 [[ 10  40]
 [ 30  80]
 [ 50 120]] Shape: (3, 2)


In [53]:
# Incompatible broadcasting and way to fix it
array_ones = np.ones((4, 3))
array_ones_1 = np.ones((4,2))

try:
    print(array_ones + array_ones_1)
except ValueError as err:
    print(f"Error: {err}, \n")

# Fix
a = np.ones((4, 3))  # Shape (4, 3)
print(a, f"Shape: {a.shape}")

b = np.array([1, 2, 3, 4])  # Shape (4,)
print(b, f"Shape: {b.shape}")

# Directly adding a + b fails because (4,) pads to (1, 4), which doesn't match (4, 3)
# Fix: Insert a new dimension to make b shape (4, 1)
b_fixed = b[:, np.newaxis]  # Shape becomes (4, 1)
print(b_fixed, f"Shape: {b_fixed.shape}")

print(f"Finally: {a+b_fixed}, Shape: {(a + b_fixed).shape}")
# Output: (4, 3)


Error: operands could not be broadcast together with shapes (4,3) (4,2) , 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] Shape: (4, 3)
[1 2 3 4] Shape: (4,)
[[1]
 [2]
 [3]
 [4]] Shape: (4, 1)
Finally: [[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]], Shape: (4, 3)
